version: '3.8'
services:
  medvoll-db:
    image: mysql:latest
    container_name: mysql-medvoll
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - dev-network
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:    

networks:
  dev-network:

